### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by fnattino** [EcoExtreML/Emulator#10]
Hi @QianqianHan96, Sarah suggested to point out possible points of improvement for this repository - so I will be opening few issues here :) 

It would be handy to have an `environment.yml` (if using conda) or `requirements.txt` (if using pip) with all the project dependencies, so that anyone cloning the repository can easily create a working environment to run the notebooks.

**Comment by QianqianHan96** [comment]
Hi Francesco, 
Thanks for pointing this, the environment.yml is in https://github.com/EcoExtreML/Emulator/blob/main/2daskParallel/environment.yaml now. Where should I put it or put this link in README file?

**Comment by fnattino** [comment]
Nice, maybe just place it in the root directory of the repository? It is a somewhat standard place where to keep this file, and immediately visible to people cloning the repository :)

**Comment by QianqianHan96** [comment]
Thanks. I already put it in the root directory now. Let me know if it works for you or not.

**Comment by fnattino** [comment]
Perfect, thanks!
