### ISSUE TITLE
data folder

### ISSUE THREAD

**Issue by fnattino** [EcoExtreML/Emulator#11]
It can be helpful to separate input data from code and other repository files - maybe you can create a `data` directory where to put, for instance, the Europe boundary shapefile?

**Comment by QianqianHan96** [comment]
Thanks for your advice. I already created a directory named "input_data" and put the Europe boundary shapefile in it. Other big files we will plan to upload them to GitHub later?

**Comment by fnattino** [comment]
Thanks! Unfortunately big data cannot be uploaded to GitHub, and having them here would also not be handy (imagine copying all dataset whenever you are cloning the repository).
