### ISSUE TITLE
Path to the RF model

### ISSUE THREAD

**Issue by fnattino** [EcoExtreML/Emulator#14]
I see two paths are employed to reach the RF model in the notebooks: `/gpfs/work2/0/ttse0619/qianqian/global_data_Qianqian/3RF_train/RFLEH-LAI-hc-CO2-SSM-Vcmo-IGBP_multi7_1core_snellius0629.pkl` (used at the beginning of the notebook) and `/gpfs/work1/0/einf2480/global_data_Qianqian/RF_train/RFLEH-LAI-hc-CO2-SSM-Vcmo-IGBP_multi7_1core_snellius0629.pkl` (used in the actual calculation, passed as argument to the `map_blocks` function). I suppose the latter is a directory associated to the former SURF project, as I do not have access to it? Should we just use the former and drop the second? 

It would be best to define the path using the `workingPath` variable, so that if that is updated, all the path instances are adjusted accordingly.

**Comment by QianqianHan96** [comment]
Hi Francesco,

Sorry I did not notice this problem, yes, you are right, the latter path is the former SURF project, it worked for me, so I did not realize to change this path. I agree that we keep the former one which is the new SURF project path.

Defining the path using workingPath variable is a good idea. I will update the notebook.

**Comment by fnattino** [comment]
Great, thanks! 😃

**Comment by QianqianHan96** [comment]
#19
