### ISSUE TITLE
Silent the user warning of sklearn during inference

### ISSUE THREAD

**Issue by geek-yang** [EcoExtreML/Emulator#16]
Currently when performing inference with the random forest model, we receive the following warnings (e.g. check cell 39 in this [notebook](https://github.com/EcoExtreML/Emulator/blob/main/2daskParallel/0921_1year_10degree.ipynb)):

```py
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
```

This is caused by the fact that the training data is pandas dataframe with feature names, and the testing data is numpy array without feature names:
```py
...
    CO2_line = ds_ss[8,:,:,:].to_numpy().reshape(1, ds_ss.latitude.size*ds_ss.longitude.size*ds_ss.time.size)
    SSM_line = ds_ss[9,:,:,:].to_numpy().reshape(1, ds_ss.latitude.size*ds_ss.longitude.size*ds_ss.time.size)

    features_arr = np.concatenate((Rin_line, Rli_line, p_line, Ta_line,ea_line, u_line, Precip_msr_line,
                                   LAI_line, hc_line, CO2_line, SSM_line, Vcmo_line,
                                   IGBP1, IGBP2, IGBP3,IGBP4,IGBP5,IGBP6,IGBP7,IGBP8,IGBP9,IGBP10,IGBP11))
    features_arr = features_arr.transpose()
...
    model = load_model(path_model)
    
    # model = path_model
    estimated_LEH = model.predict(features_arr)
...
```
Here is [a similar issue with solution](https://stackoverflow.com/questions/69326639/sklearn-warning-valid-feature-names-in-version-1-0) on stackoverflow. To fix this, we need to turn `features_arr` into pandas dataframe with feature names as column names.

**Comment by QianqianHan96** [comment]
Thanks Yang for your advice, I will fix this problem soon.
